version: '3.8'
services:
  db:
    image: postgres:14
    container_name: pilots_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pilots_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 